# GST on Rigetti Backends with PyGSTi
The purpose of this notebook is to use the data collected from a GST experiment that has been read into the `rigetti_first_run` directory and perform GST on it. 

This code was mostly taken from the tutorial notebook [UnitaryFundDemoNotebook1.ipynb
](https://zenodo.org/record/5715199#.Yr_TOUjMLJF). 

In [1]:
#PyGSTi tools
import pygsti
from pygsti.modelpacks import smq1Q_XZ

#Mitiq tools
from mitiq.pec import NoisyOperation, NoisyBasis, execute_with_pec
from mitiq.pec.representations.optimal import find_optimal_representation, find_optimal_representation_super

from mitiq import QPROGRAM
from mitiq.interface import convert_to_mitiq
from mitiq.pec.types import NoisyBasis, OperationRepresentation
from mitiq.pec.channels import matrix_to_vector, kraus_to_super
from mitiq.pec.channels import choi_to_super, _circuit_to_choi

#Helper libraries
from typing import cast, List, Optional
import numpy as np
import numpy.typing as npt
from scipy.optimize import minimize, LinearConstraint

#make numpy matrices easier to read
np.set_printoptions(precision=3, suppress=True)

# Qiskit
import qiskit
from qiskit.quantum_info import PTM, SuperOp, Kraus, Pauli, Operator
from qiskit import QuantumCircuit, QuantumRegister
from qiskit.test.mock import *
from qiskit.providers.fake_provider import *
from qiskit.providers.aer import AerSimulator, QasmSimulator, Aer
from qiskit.providers.aer.noise import phase_amplitude_damping_error
from qiskit.providers.aer.noise.noise_model import NoiseModel
from qiskit.quantum_info.operators.channel.transformations import *
from qiskit.quantum_info.operators.channel.quantum_channel import QuantumChannel
from qiskit.quantum_info.operators.channel.transformations import _choi_to_kraus, _kraus_to_superop
from qiskit.quantum_info.operators.channel.transformations import _kraus_to_choi, _choi_to_superop

# Cirq library used as a frontend for interfacing Mitiq
import cirq
from cirq import kraus

from qutip import *
from qutip.qip.operations import expand_operator
from qutip.steadystate import steadystate

In [2]:
z2 = expand_operator(sigmaz(), 3, 0) * expand_operator(sigmaz(), 3, 1) * expand_operator(sigmaz(), 3, 2)
x1 = expand_operator(sigmax(), 3, 0)
x2 = expand_operator(sigmax(), 3, 1)
x3 = expand_operator(sigmax(), 3, 2)

In [3]:
error = phase_amplitude_damping_error(0.001,0.001)
noise_model = NoiseModel()
noise_model.add_all_qubit_quantum_error(error, ['id'])

In [4]:
for i, j in enumerate(Qobj((SuperOp(error).tensor(SuperOp(np.identity(4))).data + SuperOp(np.identity(4)).tensor(SuperOp(error)).data)/2).full()):
    for k, l in enumerate(j):
        if l > 0:
            print(i, k, l)

0 0 (0.9999999999999997+0j)
0 5 (0.0004999999999999999+0j)
0 10 (0.0004999999999999999+0j)
1 1 (0.9994997497496867+0j)
1 11 (0.0004999999999999999+0j)
2 2 (0.9994997497496867+0j)
2 7 (0.0004999999999999999+0j)
3 3 (0.9989994994993737+0j)
4 4 (0.9994997497496867+0j)
4 14 (0.0004999999999999999+0j)
5 5 (0.9994999999999997+0j)
5 15 (0.0004999999999999999+0j)
6 6 (0.9989994994993737+0j)
7 7 (0.9989997497496867+0j)
8 8 (0.9994997497496867+0j)
8 13 (0.0004999999999999999+0j)
9 9 (0.9989994994993737+0j)
10 10 (0.9994999999999997+0j)
10 15 (0.0004999999999999999+0j)
11 11 (0.9989997497496867+0j)
12 12 (0.9989994994993737+0j)
13 13 (0.9989997497496867+0j)
14 14 (0.9989997497496867+0j)
15 15 (0.9989999999999998+0j)


In [5]:
Qobj(SuperOp(error).tensor(SuperOp(np.identity(4))).data)

Quantum object: dims = [[16], [16]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.001 0.
  0.    0.    0.    0.   ]
 [0.    1.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.001
  0.    0.    0.    0.   ]
 [0.    0.    0.999 0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.   ]
 [0.    0.    0.    0.999 0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.   ]
 [0.    0.    0.    0.    1.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.001 0.   ]
 [0.    0.    0.    0.    0.    1.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.001]
 [0.    0.    0.    0.    0.    0.    0.999 0.    0.    0.    0.    0.
  0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.999 0.    0.    0.    0.
  0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.999 0.    0.    0.
  0.    0.    0.    0.   ]
 [0.    0.    0.    

In [162]:
for i, j in enumerate(Qobj(SuperOp(error).tensor(SuperOp(np.identity(4))).data).full()):
    for k, l in enumerate(j):
        if l > 0:
            print(i, k, l)

0 0 (0.9999999999999997+0j)
0 10 (0.0009999999999999998+0j)
1 1 (0.9999999999999997+0j)
1 11 (0.0009999999999999998+0j)
2 2 (0.9989994994993737+0j)
3 3 (0.9989994994993737+0j)
4 4 (0.9999999999999997+0j)
4 14 (0.0009999999999999998+0j)
5 5 (0.9999999999999997+0j)
5 15 (0.0009999999999999998+0j)
6 6 (0.9989994994993737+0j)
7 7 (0.9989994994993737+0j)
8 8 (0.9989994994993737+0j)
9 9 (0.9989994994993737+0j)
10 10 (0.9989999999999998+0j)
11 11 (0.9989999999999998+0j)
12 12 (0.9989994994993737+0j)
13 13 (0.9989994994993737+0j)
14 14 (0.9989999999999998+0j)
15 15 (0.9989999999999998+0j)


## Read data from experiment
This data was written by the `get_gst_data.ipynb` file.

In [2]:
# Usa data from first run
data = pygsti.io.read_data_from_dir('experiment_data/rigetti_first_run')

# Use data from second run
# data = pygsti.io.read_data_from_dir('experiment_data_all/second_experiment_run_data/experiment_data/rigetti_first_run')


## Run GST on the data

In this subsection we impose that RZ  must be equal to the ideal operation.

This is procedure is adapted from page 3 of https://arxiv.org/abs/2002.12476.


In [3]:
# Run GST assuming a perfect rz gate.
target_mdl = smq1Q_XZ.target_model()
rz_matrix = target_mdl[('Gzpi2',0)].to_dense()
dense_rz = pygsti.modelmembers.operations.DenseOperator(rz_matrix, evotype="default")
target_mdl[('Gzpi2',0)] = dense_rz.copy()

results = pygsti.protocols.GST(target_mdl, gaugeopt_suite=None).run(data)

--- Iterative GST: Iter 1 of 6  52 circuits ---: 
  MatrixLayout: 1 processors divided into 1 x 1 (= 1) grid along circuit and parameter directions.
     1 atoms, parameter block size limits (None,)
  *** Distributing 1 atoms to 1 atom-processing groups (1 cores) ***
      More atom-processors than hosts: each host gets ~1 atom-processors
      Atom-processors already occupy a single node, dividing atom-processor into 1 param-processors.
  *** Divided 1-host atom-processor (~1 procs) into 1 param-processing groups ***
  --- chi2 GST ---
  Sum of Chi^2 = 93.5413 (52 data params - 28 (approx) model params = expected mean of 24; p-value = 3.70919e-10)
  Completed in 0.2s
  Iteration 1 took 0.3s
  
--- Iterative GST: Iter 2 of 6  96 circuits ---: 
  MatrixLayout: 1 processors divided into 1 x 1 (= 1) grid along circuit and parameter directions.
     1 atoms, parameter block size limits (None,)
  *** Distributing 1 atoms to 1 atom-processing groups (1 cores) ***
      More atom-processors t

In [4]:
model = results.estimates['GateSetTomography'].models['final iteration estimate']
print("Rx Pauli transfer matrix:\n", model.operations[('Gxpi2', 0)].to_dense())
print("Rz Pauli transfer matrix:\n", model.operations[('Gzpi2', 0)].to_dense())

Rx Pauli transfer matrix:
 [[ 0.999  0.002 -0.011  0.007]
 [ 0.01   0.989  0.062 -0.064]
 [ 0.062 -0.057  0.012 -0.974]
 [ 0.06  -0.059  0.976  0.016]]
Rz Pauli transfer matrix:
 [[ 1.  0.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  0.  1.]]


## Get noisy superoperators

In [6]:
# Convert Pauli transfer matrix to superoperator
superop_rx = SuperOp(PTM(model.operations[('Gxpi2', 0)].to_dense())).data.conj()  # conj depends on convention
superop_rz = SuperOp(PTM(model.operations[('Gzpi2', 0)].to_dense())).data.conj()  # conj depends on convention



print("Rx superoperator matrix:\n", superop_rx)
print("Rz superoperator matrix:\n", superop_rz)


NameError: name 'model' is not defined

## Get ideal superoperators. Method 1.

In [9]:
qb = [cirq.LineQubit(x) for x in range(0, 2)]

In [3]:
qb[1]

cirq.LineQubit(1)

In [10]:
def Rzz(q0, q1, theta):
    yield cirq.CNOT(q0, q1)
    yield cirq.rz(theta).on(q1)
    yield cirq.CNOT(q0, q1)
    
def Ryy(q0, q1, theta):
    yield [cirq.ZPowGate(exponent=0.5).on(q0),cirq.ZPowGate(exponent=0.5).on(q1)]
    yield [cirq.H(q0), cirq.H(q1)]
    yield cirq.CNOT(q0, q1)
    yield cirq.rz(theta).on(q1)
    yield cirq.CNOT(q0, q1)
    yield [cirq.HPowGate(exponent=-1).on(q0), cirq.HPowGate(exponent=-1).on(q1)]
    yield [cirq.ZPowGate(exponent=-0.5).on(q0),cirq.ZPowGate(exponent=-0.5).on(q1)]
    
def Rxx(q0, q1, theta):
    yield [cirq.H(q0), cirq.H(q1)]
    yield cirq.CNOT(q0, q1)
    yield cirq.rz(theta).on(q1)
    yield cirq.CNOT(q0, q1)
    yield [cirq.HPowGate(exponent=-1).on(q0), cirq.HPowGate(exponent=-1).on(q1)]

In [11]:
dt = 0.005*np.pi/2
thet = -1 * dt

# For 1 qubit
circuitZ = cirq.Circuit()
circuitZ.append(cirq.rz(thet).on(qb[0]))

circuitX = cirq.Circuit()
circuitX.append(cirq.rx(thet).on(qb[0]))

# Create ideal operations as Cirq circuits
circuitrXI = cirq.Circuit()
circuitrXI.append(cirq.rx(thet).on(qb[0]))
circuitrXI.append(cirq.I(qb[1]))
circuitIrX = cirq.Circuit()
circuitIrX.append(cirq.rx(thet).on(qb[1]))
circuitIrX.append(cirq.I(qb[0]))
circuitrZI = cirq.Circuit()
circuitrZI.append(cirq.rz(thet).on(qb[0]))
circuitrZI.append(cirq.I(qb[1]))
circuitIrZ = cirq.Circuit()
circuitIrZ.append(cirq.rz(thet).on(qb[1]))
circuitIrZ.append(cirq.I(qb[0]))

circuitXI = cirq.Circuit()
circuitXI.append(cirq.X(qb[0]))
circuitXI.append(cirq.I(qb[1]))
circuitIX = cirq.Circuit()
circuitIX.append(cirq.X(qb[1]))
circuitIX.append(cirq.I(qb[0]))

circuitsXI = cirq.Circuit()
circuitsXI.append(cirq.XPowGate(exponent=0.5).on(qb[0]))
circuitsXI.append(cirq.I(qb[1]))
circuitIsX = cirq.Circuit()
circuitIsX.append(cirq.XPowGate(exponent=0.5).on(qb[1]))
circuitIsX.append(cirq.I(qb[0]))

circuitZZ = cirq.Circuit()
cirq_rzz = circuitZZ.append(Rzz(qb[0], qb[1], thet))
# cirq_rzz = cirq.Circuit(cirq.rzz(np.pi / 2).on(cirq.LineQubit(0)))
circuitXX = cirq.Circuit()
cirq_rxx = circuitXX.append(Rxx(qb[0], qb[1], thet))
# cirq_rxx = cirq.Circuit(cirq.rx(np.pi / 2).on(cirq.LineQubit(0)))
circuitYY = cirq.Circuit()
cirq_ryy = circuitYY.append(Ryy(qb[0], qb[1], thet))

In [12]:
circuitZZ

0: ───@─────────────────@───
      │                 │
1: ───X───Rz(-0.002π)───X───

In [13]:
from mitiq.pec.channels import choi_to_super, _circuit_to_choi

test_ZZ = choi_to_super(_circuit_to_choi(circuitZZ))

In [553]:
from mitiq.pec.channels import choi_to_super, _circuit_to_choi

superop_rxx_mitiq = choi_to_super(_circuit_to_choi(circuitXX))
superop_ryy_mitiq = choi_to_super(_circuit_to_choi(circuitYY))
superop_rzz_mitiq = choi_to_super(_circuit_to_choi(circuitZZ))
# print(superop_rxx_mitiq)
# print(superop_ryy_mitiq)
superop_rxx_mitiq

array([[1.+0.j   , 0.+0.j   , 0.+0.j   , 0.-0.008j, 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.008j, 0.+0.j   , 0.+0.j   , 0.+0.j   ],
       [0.+0.j   , 1.+0.j   , 0.-0.008j, 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.008j, 0.+0.j   , 0.+0.j   ],
       [0.+0.j   , 0.-0.008j, 1.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.008j, 0.+0.j   ],
       [0.-0.008j, 0.+0.j   , 0.+0.j   , 1.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.008j],
       [0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 1.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.-0.008j, 0.+0.008j, 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j 

## Get superoperators. Method 2

In [15]:
superop_rxx_cirq = cirq.kraus_to_superoperator(cirq.kraus(circuitXX))
superop_rzz_cirq = cirq.kraus_to_superoperator(cirq.kraus(circuitZZ))
print(superop_rxx_cirq)
print(superop_rzz_cirq)

[[1.+0.j    0.+0.j    0.+0.j    0.-0.004j 0.+0.j    0.+0.j    0.+0.j
  0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.004j 0.+0.j
  0.+0.j    0.+0.j   ]
 [0.+0.j    1.+0.j    0.-0.004j 0.+0.j    0.+0.j    0.+0.j    0.+0.j
  0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.004j
  0.+0.j    0.+0.j   ]
 [0.+0.j    0.-0.004j 1.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j
  0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j
  0.+0.004j 0.+0.j   ]
 [0.-0.004j 0.+0.j    0.+0.j    1.+0.j    0.+0.j    0.+0.j    0.+0.j
  0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j
  0.+0.j    0.+0.004j]
 [0.+0.j    0.+0.j    0.+0.j    0.+0.j    1.+0.j    0.+0.j    0.+0.j
  0.-0.004j 0.+0.004j 0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j
  0.+0.j    0.+0.j   ]
 [0.+0.j    0.+0.j    0.+0.j    0.+0.j    0.+0.j    1.+0.j    0.-0.004j
  0.+0.j    0.+0.j    0.+0.004j 0.+0.j    0.+0.j    0.+0.j    0.+0.j
  0.+0.j    0.+0.j   ]
 [0.+0.j    0.+0.j    0.+0.j

## Get superoperators from QuTiP (qiskit too)

In [16]:
## This is the \sigma_+ \sigma_- part:
n_qubits = 2
al = 1
L = 0
for n in range(n_qubits):
    c_op_left = expand_operator(sigmap(), n_qubits, n)
    c_op_right = expand_operator(sigmam(), n_qubits, n)
    L += al*sprepost(c_op_left, c_op_right)
    both = -0.5 * al * c_op_right * c_op_left
    L += spre(both)
    L += spost(both)

In [17]:
L

Quantum object: dims = [[[2, 2], [2, 2]], [[2, 2], [2, 2]]], shape = (16, 16), type = super, isherm = False
Qobj data =
[[ 0.   0.   0.   0.   0.   1.   0.   0.   0.   0.   1.   0.   0.   0.
   0.   0. ]
 [ 0.  -0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.   1.   0.   0.
   0.   0. ]
 [ 0.   0.  -0.5  0.   0.   0.   0.   1.   0.   0.   0.   0.   0.   0.
   0.   0. ]
 [ 0.   0.   0.  -1.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   0. ]
 [ 0.   0.   0.   0.  -0.5  0.   0.   0.   0.   0.   0.   0.   0.   0.
   1.   0. ]
 [ 0.   0.   0.   0.   0.  -1.   0.   0.   0.   0.   0.   0.   0.   0.
   0.   1. ]
 [ 0.   0.   0.   0.   0.   0.  -1.   0.   0.   0.   0.   0.   0.   0.
   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.  -1.5  0.   0.   0.   0.   0.   0.
   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.  -0.5  0.   0.   0.   0.   1.
   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.   0.  -1.   0.   0.   0.   0.
   0.   0. ]
 [ 0.   0.   0.   0.   0.   0.   0.   0.

In [18]:
ga = 0.003; t = 1
ell = Qobj(ga*t*L).expm()
ell

Quantum object: dims = [[[2, 2], [2, 2]], [[2, 2], [2, 2]]], shape = (16, 16), type = super, isherm = False
Qobj data =
[[1.    0.    0.    0.    0.    0.003 0.    0.    0.    0.    0.003 0.
  0.    0.    0.    0.   ]
 [0.    0.999 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.003
  0.    0.    0.    0.   ]
 [0.    0.    0.999 0.    0.    0.    0.    0.003 0.    0.    0.    0.
  0.    0.    0.    0.   ]
 [0.    0.    0.    0.997 0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.999 0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.003 0.   ]
 [0.    0.    0.    0.    0.    0.997 0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.003]
 [0.    0.    0.    0.    0.    0.    0.997 0.    0.    0.    0.    0.
  0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.996 0.    0.    0.    0.
  0.    0.    0.    0.   ]
 [0.    0.    0.    0.    0.    0.    0.    0.    0.999 0.    0.    0.
  0.    0.003 0.    0.

In [19]:
## This is the \sigma_+ \sigma_- part:
nk = 2
lz = 0
al = 1
be = 1
for n in range(nk):
    c_op_left = expand_operator(sigmap(), nk, n)
    c_op_right = expand_operator(sigmam(), nk, n)
    z_op_left = expand_operator(sigmaz(), nk, n)
    z_op_right = expand_operator(sigmaz(), nk, n)
    lz += al * sprepost(c_op_left, c_op_right)
    lz += be * sprepost(z_op_left, z_op_right)
    both = -0.5 * al * c_op_right * c_op_left
    bothz = -0.5 * be * z_op_right * z_op_left
    lz += spre(both)
    lz += spost(both)
    lz += spre(bothz)
    lz += spost(bothz)

In [20]:
de = 0.001; t = 1
L_AD = Qobj(de*t*lz).expm()
# L_AD

In [21]:
## 1 qubit stuff
qcrz = QuantumCircuit(1)
qcrz.rz(thet, 0)
qcrx = QuantumCircuit(1)
qcrx.rx(thet, 0)

qcx = QuantumCircuit(1)
qcx.x(0)

qcsx = QuantumCircuit(1)
qcsx.sx(0)

## 2 qubit stuff
# 1 qubit gates on 2 qubits
qcrzi = QuantumCircuit(2)
qcrzi.rz(thet, 0)
qcirz = QuantumCircuit(2)
qcirz.rz(thet, 1)
qcrxi = QuantumCircuit(2)
qcrxi.rx(thet, 0)
qcirx = QuantumCircuit(2)
qcirx.rx(thet, 1)

qcxi = QuantumCircuit(2)
qcxi.x(0)
qcix = QuantumCircuit(2)
qcix.x(1)

qcsxi = QuantumCircuit(2)
qcsxi.sx(0)
qcisx = QuantumCircuit(2)
qcisx.sx(1)

# the 2 qubit gates to simulate
qczz = QuantumCircuit(2)
qczz.rzz(thet, 0, 1)
qcxx = QuantumCircuit(2)
qcxx.rxx(thet, 0, 1)
qcyy = QuantumCircuit(2)
qcyy.ryy(thet, 0, 1)

qccx = QuantumCircuit(2)
qccx.cx(0, 1)

In [22]:
rzSupOp = Qobj(SuperOp(qcrz).data).tidyup(atol=1e-10).full().conj()
rxSupOp = Qobj(SuperOp(qcrx).data).tidyup(atol=1e-10).full().conj()

In [332]:
noisy_rz = rzSupOp @ ell.full()
noisy_rx = rxSupOp @ ell.full()

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 16 is different from 4)

In [23]:
rrziSupOp = Qobj(SuperOp(qcrzi).data).tidyup(atol=1e-10).full().conj()
rrxiSupOp = Qobj(SuperOp(qcrxi).data).tidyup(atol=1e-10).full().conj()
rirzSupOp = Qobj(SuperOp(qcirz).data).tidyup(atol=1e-10).full().conj()
rirxSupOp = Qobj(SuperOp(qcirx).data).tidyup(atol=1e-10).full().conj()
rxiSupOp = Qobj(SuperOp(qcxi).data).tidyup(atol=1e-10).full().conj()
rixSupOp = Qobj(SuperOp(qcix).data).tidyup(atol=1e-10).full().conj()
rsxiSupOp = Qobj(SuperOp(qcsxi).data).tidyup(atol=1e-10).full().conj()
risxSupOp = Qobj(SuperOp(qcisx).data).tidyup(atol=1e-10).full().conj()

In [24]:
noisy_rzi = rrziSupOp @ ell.full()
noisy_riz = rirzSupOp @ ell.full()
noisy_rxi = rrxiSupOp @ ell.full()
noisy_rix = rirxSupOp @ ell.full()
noisy_xi = rxiSupOp @ ell.full()
noisy_ix = rixSupOp @ ell.full()
noisy_sxi = rsxiSupOp @ ell.full()
noisy_isx = risxSupOp @ ell.full()

In [25]:
noisy_rzi_ad = rrziSupOp @ L_AD.full()
noisy_riz_ad = rirzSupOp @ L_AD.full()
noisy_rxi_ad = rrxiSupOp @ L_AD.full()
noisy_rix_ad = rirxSupOp @ L_AD.full()
noisy_xi_ad = rxiSupOp @ L_AD.full()
noisy_ix_ad = rixSupOp @ L_AD.full()
noisy_sxi_ad = rsxiSupOp @ L_AD.full()
noisy_isx_ad = risxSupOp @ L_AD.full()

In [26]:
rzzSupOp = Qobj(SuperOp(qczz).data).tidyup(atol=1e-10).full().conj()
rxxSupOp = Qobj(SuperOp(qcxx).data).tidyup(atol=1e-10).full().conj()
ryySupOp = Qobj(SuperOp(qcyy).data).tidyup(atol=1e-10).full().conj()

In [27]:
noisy_rzz = rzzSupOp @ ell.full()
noisy_rxx = rxxSupOp @ ell.full()
noisy_ryy = ryySupOp @ ell.full()

In [28]:
noisy_rzz_ad = rzzSupOp @ L_AD.full()
noisy_rxx_ad = rxxSupOp @ L_AD.full()
noisy_ryy_ad = ryySupOp @ L_AD.full()

In [29]:
Qobj(noisy_rzz)

Quantum object: dims = [[16], [16]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[1.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.003+0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.003+0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j   ]
 [0.   +0.j    0.998+0.008j 0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j    0.003+0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.998+0.008j 0.   +0.j    0.   +0.j
  0.   +0.j    0.   +0.j    0.003+0.j    0.   +0.j    0.   +0.j
  0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.   +0.j    0.997+0.j    0.   +0.j
  0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.998-0.008j
  0.  

In [30]:
Qobj(noisy_rzz_ad)

Quantum object: dims = [[16], [16]], shape = (16, 16), type = oper, isherm = False
Qobj data =
[[1.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.001+0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.001+0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j   ]
 [0.   +0.j    0.997+0.008j 0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j    0.001+0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.997+0.008j 0.   +0.j    0.   +0.j
  0.   +0.j    0.   +0.j    0.001+0.j    0.   +0.j    0.   +0.j
  0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.   +0.j    0.995+0.j    0.   +0.j
  0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j
  0.   +0.j   ]
 [0.   +0.j    0.   +0.j    0.   +0.j    0.   +0.j    0.997-0.008j
  0.  

## Define the basis of noisy operations

In [31]:
# Create noisy operations as Mitiq NoisyOperation objects for 1 qubit
# mitiq_noisy_rx = NoisyOperation(circuitX, noisy_rx)
# mitiq_noisy_rz = NoisyOperation(circuitZ, noisy_rz)

# Combine into basis object, 1 qubit
# base_noisy_basis = NoisyBasis(mitiq_noisy_rx, mitiq_noisy_rz)

# Create noisy operations as Mitiq NoisyOperation objects for 2 qubits
# mitiq_noisy_rrxi = NoisyOperation(circuitrXI, noisy_rxi_ad)
# mitiq_noisy_rirx = NoisyOperation(circuitIrX, noisy_rix_ad)
# mitiq_noisy_rrzi = NoisyOperation(circuitrZI, noisy_rzi_ad)
mitiq_noisy_rrzi = NoisyOperation(circuitrZI, rrziSupOp)

# mitiq_noisy_rirz = NoisyOperation(circuitIrZ, noisy_riz_ad)
mitiq_noisy_rirz = NoisyOperation(circuitIrZ, rirzSupOp)

mitiq_noisy_rxx = NoisyOperation(circuitXX, noisy_rxx_ad)
mitiq_noisy_ryy = NoisyOperation(circuitYY, noisy_ryy_ad)
mitiq_noisy_rzz = NoisyOperation(circuitZZ, noisy_rzz_ad)

mitiq_noisy_xi = NoisyOperation(circuitXI, noisy_xi_ad)
mitiq_noisy_ix = NoisyOperation(circuitIX, noisy_ix_ad)
mitiq_noisy_sxi = NoisyOperation(circuitsXI, noisy_sxi_ad)
mitiq_noisy_isx = NoisyOperation(circuitIsX, noisy_isx_ad)

# Combine into basis object, 2 qubits: mitiq_noisy_rrxi, mitiq_noisy_rirx,
base_noisy_basis_zz = NoisyBasis(mitiq_noisy_rrzi, mitiq_noisy_rirz, mitiq_noisy_xi, 
                                 mitiq_noisy_ix, mitiq_noisy_sxi, mitiq_noisy_isx,
                                 mitiq_noisy_rzz)
base_noisy_basis_yy = NoisyBasis(mitiq_noisy_rrzi, mitiq_noisy_rirz, mitiq_noisy_xi, 
                                 mitiq_noisy_ix, mitiq_noisy_sxi, mitiq_noisy_isx,
                                 mitiq_noisy_ryy)
base_noisy_basis_xx = NoisyBasis(mitiq_noisy_rrzi, mitiq_noisy_rirz, mitiq_noisy_xi, 
                                 mitiq_noisy_ix, mitiq_noisy_sxi, mitiq_noisy_isx,
                                 mitiq_noisy_rxx)

# Extend basis to squences of noisy gates
noisy_basis_zz = NoisyBasis(
    *base_noisy_basis_zz.get_sequences(1),
    *base_noisy_basis_zz.get_sequences(2),
)
noisy_basis_yy = NoisyBasis(
    *base_noisy_basis_yy.get_sequences(1),
    *base_noisy_basis_yy.get_sequences(2),
)
noisy_basis_xx = NoisyBasis(
    *base_noisy_basis_xx.get_sequences(1),
    *base_noisy_basis_xx.get_sequences(2),
)

print("Sequeces of noisy operations to be used as a basis for PEC:")
for elem in noisy_basis_zz.elements:
    print(elem)

Sequeces of noisy operations to be used as a basis for PEC:
0: ───I───────I───

1: ───X^0.5───X───
0: ───I─────────────I───

1: ───Rz(-0.002π)───X───
0: ───@─────────────────@───
      │                 │
1: ───X───Rz(-0.002π)───X───
0: ───Rz(-0.002π)───

1: ───I─────────────
0: ───X───@─────────────────@───
          │                 │
1: ───I───X───Rz(-0.002π)───X───
0: ───X───X───

1: ───I───I───
0: ───I─────────────I─────────────

1: ───Rz(-0.002π)───Rz(-0.002π)───
0: ───X───X^0.5───

1: ───I───I───────
0: ───Rz(-0.002π)───I───────

1: ───I─────────────X^0.5───
0: ───@─────────────────@───X^0.5───
      │                 │
1: ───X───Rz(-0.002π)───X───I───────
0: ───@─────────────────@───X───
      │                 │
1: ───X───Rz(-0.002π)───X───I───
0: ───X───I───────

1: ───I───X^0.5───
0: ───I───@─────────────────@───
          │                 │
1: ───X───X───Rz(-0.002π)───X───
0: ───I───────@─────────────────@───
              │                 │
1: ───X^0.5───X───Rz(-0.002π)

In [36]:
mitiq_noisy_rzz.circuit('cirq')

0: ───@─────────────────@───
      │                 │
1: ───X───Rz(-0.002π)───X───

## Compute optimal representation

In [37]:
superop_rzz_cirq

array([[1.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ],
       [0.+0.j   , 1.+0.008j, 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ],
       [0.+0.j   , 0.+0.j   , 1.+0.008j, 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ],
       [0.+0.j   , 0.+0.j   , 0.+0.j   , 1.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ],
       [0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 1.-0.008j, 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j   ,
        0.+0.j   , 0.+0.j   , 0.+0.j   , 0.+0.j 

In [38]:
noisy_rzz

array([[1.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ,
        0.   +0.j   , 0.003+0.j   , 0.   +0.j   , 0.   +0.j   ,
        0.   +0.j   , 0.   +0.j   , 0.003+0.j   , 0.   +0.j   ,
        0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.998+0.008j, 0.   +0.j   , 0.   +0.j   ,
        0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ,
        0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.003+0.j   ,
        0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.998+0.008j, 0.   +0.j   ,
        0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.003+0.j   ,
        0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ,
        0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ],
       [0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.997+0.j   ,
        0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ,
        0.   +0.j   , 0.   +0.j   , 0.   +0.j   , 0.   +0.j   ,
        0.   +0.j   , 0.   +0.j   , 0

In [39]:
# Get optimal representation in terms of noisy gates
# optimal_rep = find_optimal_representation(circuitZZ, noisy_basis, tol=.001) #circuitZZ
optimal_rep_zz = find_optimal_representation_super(circuitZZ, noisy_rzz, noisy_basis_zz, tol=.003)

print(optimal_rep_zz)
print("Overhead: ", optimal_rep_zz.norm) # Hopefully close to 1

0: ───@─────────────────@───
      │                 │
1: ───X───Rz(-0.002π)───X─── = 

0.715
0: ───@─────────────────@───
      │                 │
1: ───X───Rz(-0.002π)───X───

+0.106
0: ───Rz(-0.002π)───

1: ───I─────────────

+0.006
0: ───X───X───

1: ───I───I───

+0.005
0: ───I─────────────I─────────────

1: ───Rz(-0.002π)───Rz(-0.002π)───

+0.106
0: ───I─────────────

1: ───Rz(-0.002π)───

+0.006
0: ───I───I───

1: ───X───X───

+0.005
0: ───I─────────────@─────────────────@───
                    │                 │
1: ───Rz(-0.002π)───X───Rz(-0.002π)───X───

+0.008
0: ───Rz(-0.002π)───I─────────────

1: ───I─────────────Rz(-0.002π)───

+0.005
0: ───Rz(-0.002π)───Rz(-0.002π)───

1: ───I─────────────I─────────────

+0.005
0: ───Rz(-0.002π)───@─────────────────@───
                    │                 │
1: ───I─────────────X───Rz(-0.002π)───X───

+0.012
0: ───@─────────────────@───@─────────────────@───
      │                 │   │                 │
1: ───X───Rz(-0.002π)───X───X─

In [40]:
# Get optimal representation in terms of noisy gates
# optimal_rep = find_optimal_representation(circuitZZ, noisy_basis, tol=.001) #circuitZZ
optimal_rep_yy = find_optimal_representation_super(circuitYY, noisy_ryy, noisy_basis_yy, tol=.003)

print(optimal_rep_yy)
print("Overhead: ", optimal_rep_yy.norm) # Hopefully close to 1

0: ───S───H───@─────────────────@───H───S^-1───
              │                 │
1: ───S───H───X───Rz(-0.002π)───X───H───S^-1─── = 

0.117
0: ───Rz(-0.002π)───

1: ───I─────────────

+0.008
0: ───I─────────────S───H───@─────────────────@───H───S^-1───
                            │                 │
1: ───Rz(-0.002π)───S───H───X───Rz(-0.002π)───X───H───S^-1───

+0.001
0: ───I───────I───

1: ───X^0.5───X───

+0.117
0: ───I─────────────

1: ───Rz(-0.002π)───

+0.009
0: ───Rz(-0.002π)───I─────────────

1: ───I─────────────Rz(-0.002π)───

+0.008
0: ───Rz(-0.002π)───S───H───@─────────────────@───H───S^-1───
                            │                 │
1: ───I─────────────S───H───X───Rz(-0.002π)───X───H───S^-1───

+0.001
0: ───X^0.5───X───

1: ───I───────I───

+0.008
0: ───S───H───@─────────────────@───H───S^-1───Rz(-0.002π)───
              │                 │
1: ───S───H───X───Rz(-0.002π)───X───H───S^-1───I─────────────

+0.008
0: ───S───H───@─────────────────@───H───S^-1───I───────────

In [42]:
# Get optimal representation in terms of noisy gates
# optimal_rep = find_optimal_representation(circuitZZ, noisy_basis, tol=.001) #circuitZZ
optimal_rep_xx = find_optimal_representation_super(circuitXX, noisy_rxx, noisy_basis_xx, tol=.003)

print(optimal_rep_xx)
print("Overhead: ", optimal_rep_xx.norm) # Hopefully close to 1

0: ───H───@─────────────────@───H───
          │                 │
1: ───H───X───Rz(-0.002π)───X───H─── = 

0.001
0: ───I─────────────H───@─────────────────@───H───
                        │                 │
1: ───Rz(-0.002π)───H───X───Rz(-0.002π)───X───H───

+0.163
0: ───Rz(-0.002π)───

1: ───I─────────────

+0.001
0: ───Rz(-0.002π)───H───@─────────────────@───H───
                        │                 │
1: ───I─────────────H───X───Rz(-0.002π)───X───H───

+0.163
0: ───I─────────────

1: ───Rz(-0.002π)───

+0.013
0: ───I─────────────Rz(-0.002π)───

1: ───Rz(-0.002π)───I─────────────

+0.635
0: ───H───@─────────────────@───H───
          │                 │
1: ───H───X───Rz(-0.002π)───X───H───

+0.007
0: ───H───@─────────────────@───H───H───@─────────────────@───H───
          │                 │           │                 │
1: ───H───X───Rz(-0.002π)───X───H───H───X───Rz(-0.002π)───X───H───

+0.013
0: ───Rz(-0.002π)───I─────────────

1: ───I─────────────Rz(-0.002π)───
Overhead:  0

In [43]:
optimal_rep_xx.norm

0.9973136859610862

In [44]:
qc = QuantumCircuit(3)

In [45]:
qc.append(yy_Return[0].circuit('qiskit'), [0, 1])

NameError: name 'yy_Return' is not defined

In [857]:
qc.decompose().draw()

q_0: ──────────────────────────────────────────────
     ┌───┐┌───┐                        ┌───┐┌─────┐
q_1: ┤ S ├┤ H ├──■──────────────────■──┤ H ├┤ Sdg ├
     ├───┤├───┤┌─┴─┐┌────────────┐┌─┴─┐├───┤├─────┤
q_2: ┤ S ├┤ H ├┤ X ├┤ Rz(-π/400) ├┤ X ├┤ H ├┤ Sdg ├
     └───┘└───┘└───┘└────────────┘└───┘└───┘└─────┘

In [840]:
yy_Return[0].circuit('qiskit').draw()

┌───┐┌───┐
q_0: ┤ I ├┤ I ├
     ├───┤├───┤
q_1: ┤ X ├┤ X ├
     └───┘└───┘

In [46]:
''' Get Trotter running. '''

zz_Return = optimal_rep_zz.sample()
print(zz_Return[2])
zz_Return[0].circuit('qiskit').draw()

0.10627526050108967


┌────────────┐
q_0: ┤ Rz(-π/400) ├
     └───┬───┬────┘
q_1: ────┤ I ├─────
         └───┘

In [1121]:
optimal_rep_yy.sample()[0].circuit('qiskit').draw()

┌───┐┌───┐                        ┌───┐┌─────┐
q_0: ┤ S ├┤ H ├──■──────────────────■──┤ H ├┤ Sdg ├
     ├───┤├───┤┌─┴─┐┌────────────┐┌─┴─┐├───┤├─────┤
q_1: ┤ S ├┤ H ├┤ X ├┤ Rz(-π/400) ├┤ X ├┤ H ├┤ Sdg ├
     └───┘└───┘└───┘└────────────┘└───┘└───┘└─────┘

In [956]:
for n in range(0, 5-1, 2):
    print(n, n+1)
for n in range(1, 5-1, 2):
    print(n, n+1)

0 1
2 3
1 2
3 4


In [47]:
def xyz_Trotter(zz: OperationRepresentation,
                yy: OperationRepresentation,
                xx: OperationRepresentation,
                N: int, 
                trots: int = 1,
                form: str = 'qiskit',
               ):
    '''
    A Trotter function. Supposed to give it the expansion for an rZZ/rYY/rXX gate,
    and it will return a list of gates selected from the expansions according to
    the probabilities derived from the expansions. Makes trots Trotter step (step
    size is determined when performing the expansion).
    
    INPUTS:
    
    zz_list :: Object that contains the expansion and coefficients of the rZZ operator.
    yy_list :: Object that contains the expansion and coefficients of the rYY operator.
    xx_list :: Object that contains the expansion and coefficients of the rXX operator.
    N :: The number of qubits.
    trots :: The number of Trotter steps to take; default is 1.
    form :: Optionally, it is possible to request non-Qiskit circuits (e.g., 'cirq').
    
    RETURNS:
    
    The Trotter circuit in Qiskit form, the total overhead of the circuit, and the final sign.
    '''
    xyz_circuit = QuantumCircuit(N)
    cardinality = 1
    gamma = 1
    for _ in range(trots):
        for ops in [zz, yy, xx]:
            for n in range(0, N-1, 2):
                gamma *= ops.norm
                temp = ops.sample()
                cardinality *= temp[1]
                xyz_circuit.append(temp[0].circuit(form), [n, n+1])
            for n in range(1, N-1, 2):
                gamma *= ops.norm
                temp = ops.sample()
                cardinality *= temp[1]
                xyz_circuit.append(temp[0].circuit(form), [n, n+1])
            xyz_circuit.barrier()
    
    return (xyz_circuit, gamma, cardinality)

In [54]:
N = 3
qc = QuantumCircuit(N)
trot_circ = xyz_Trotter(optimal_rep_zz, optimal_rep_yy, optimal_rep_xx, N, 10)
qc.append(trot_circ[0], range(N))
qc.h(range(N))
qc.measure_all()
print(trot_circ[1], trot_circ[2])
qc.decompose().decompose().draw()

0.8945188803548147 1


░ ┌───┐┌───┐     »
   q_0: ──■──────────────────■───────────────────────────░─┤ S ├┤ H ├──■──»
        ┌─┴─┐┌────────────┐┌─┴─┐                         ░ ├───┤├───┤┌─┴─┐»
   q_1: ┤ X ├┤ Rz(-π/400) ├┤ X ├──■──────────────────■───░─┤ S ├┤ H ├┤ X ├»
        └───┘└────────────┘└───┘┌─┴─┐┌────────────┐┌─┴─┐ ░ ├───┤├───┤└───┘»
   q_2: ────────────────────────┤ X ├┤ Rz(-π/400) ├┤ X ├─░─┤ S ├┤ H ├─────»
                                └───┘└────────────┘└───┘ ░ └───┘└───┘     »
meas_0: ══════════════════════════════════════════════════════════════════»
                                                                          »
meas_1: ══════════════════════════════════════════════════════════════════»
                                                                          »
meas_2: ══════════════════════════════════════════════════════════════════»
                                                                          »
«                           ┌───┐┌─────┐                                       »
«   q_0: ────────────────■──┤ H ├┤ Sdg ├───────────────────────────────────────»
«        ┌────────────┐┌─┴─┐├───┤├─────┤┌───┐┌───┐                        ┌───┐»
«   q_1: ┤ Rz(-π/400) ├┤ X ├┤ H ├┤ Sdg ├┤ S ├┤ H ├──■──────────────────■──┤ H ├»
«        └────────────┘└───┘└───┘└─────┘└───┘└───┘┌─┴─┐┌────────────┐┌─┴─┐├───┤»
«   q_2: ─────────────────────────────────────────┤ X ├┤ Rz(-π/400) ├┤ X ├┤ H ├»
«                                                 └───┘└────────────┘└───┘└───┘»
«meas_0: ══════════════════════════════════════════════════════════════════════»
«                                                                              »
«meas_1: ══════════════════════════════════════════════════════════════════════»
«                                                                              »
«meas_2: ══════════════════════════════════════════════════════════════════════»
«                                                                              »
«                ░     ┌───┐                             ┌───┐      ░      »
«   q_0: ────────░─────┤ H ├───────■──────────────────■──┤ H ├──────░───■──»
«        ┌─────┐ ░     ├───┤     ┌─┴─┐┌────────────┐┌─┴─┐├───┤┌───┐ ░ ┌─┴─┐»
«   q_1: ┤ Sdg ├─░─────┤ H ├─────┤ X ├┤ Rz(-π/400) ├┤ X ├┤ H ├┤ I ├─░─┤ X ├»
«        ├─────┤ ░ ┌───┴───┴────┐└───┘└────────────┘└───┘└───┘└───┘ ░ └───┘»
«   q_2: ┤ Sdg ├─░─┤ Rz(-π/400) ├───────────────────────────────────░──────»
«        └─────┘ ░ └────────────┘                                   ░      »
«meas_0: ══════════════════════════════════════════════════════════════════»
«                                                                          »
«meas_1: ══════════════════════════════════════════════════════════════════»
«                                                                          »
«meas_2: ══════════════════════════════════════════════════════════════════»
«                                                                          »
«                                                    ░ ┌────────────┐          »
«   q_0: ────────────────■───────────────────────────░─┤ Rz(-π/400) ├──────────»
«        ┌────────────┐┌─┴─┐                         ░ └───┬───┬────┘┌───┐┌───┐»
«   q_1: ┤ Rz(-π/400) ├┤ X ├──■──────────────────■───░─────┤ I ├─────┤ S ├┤ H ├»
«        └────────────┘└───┘┌─┴─┐┌────────────┐┌─┴─┐ ░     ├───┤     ├───┤└───┘»
«   q_2: ───────────────────┤ X ├┤ Rz(-π/400) ├┤ X ├─░─────┤ S ├─────┤ H ├─────»
«                           └───┘└────────────┘└───┘ ░     └───┘     └───┘     »
«meas_0: ══════════════════════════════════════════════════════════════════════»
«                                                                              »
«meas_1: ══════════════════════════════════════════════════════════════════════»
«                                                                              »
«meas_2: ══════════════════════════════════════════════════════════════════════»
«                                          

In [55]:
backend = QasmSimulator()

In [56]:
qc_t = qiskit.transpile(qc, backend)

In [57]:
res = backend.run(qc_t, shots=8000)

In [1059]:
N = 3
reps = 100
trot = 10
shots = 8000
backend = QasmSimulator()
dict_results = []
gamma_results = []
for _ in range(reps):
    qc = QuantumCircuit(N)
    trot_circ = xyz_Trotter(optimal_rep_zz, optimal_rep_yy, optimal_rep_xx, N, trot)
    qc.append(trot_circ[0], [i for i in range(N)])
    qc.h([i for i in range(N)])
    qc.measure_all()
    qc_t = qiskit.transpile(qc, backend)
    res = backend.run(qc_t, shots=shots)
    dict_results.append(res.result().get_counts())
    gamma_results.append(trot_circ[1] * trot_circ[2])

In [1108]:
prob_results = []
for res_dict in dict_results:
    temp_dict = {}
    for i in range(int(np.log2(len(res_dict)))):
        temp_dict[f'x{i}u'] = 0
        for key in res_dict:
            if key[i] == '0':
                temp_dict[f'x{i}u'] += res_dict[key]/8000
    prob_results.append(temp_dict)
    print((2*temp_dict['x0u'] - 1)*(2*temp_dict['x2u'] - 1)/4)

7.031249999999908e-06
7.171874999999808e-06
-1.1953125000000226e-05
4.4562499999998955e-05
2.762499999999963e-05
-1.5421874999999984e-05
-4.874999999999953e-06
9.712499999999937e-05
8.875000000000085e-06
1.5031249999999944e-05
-4.867187500000018e-05
4.9140624999999875e-05
-2.1093749999998963e-06
-6.562499999999789e-06
0.00014437500000000217
1.2000000000000354e-05
7.0000000000001236e-06
-1.4843750000000312e-05
1.2484375000000178e-05
1.1250000000000437e-06
4.259374999999961e-05
-1.9593750000000348e-05
-2.7421874999999747e-05
-2.812500000000907e-07
-9.999999999994466e-07
7.81249999999998e-06
-1.0765624999999994e-05
-1.1625000000000062e-05
-1.5312500000000318e-05
-2.4999999999997267e-07
2.7546875000000343e-05
1.4000000000000025e-05
-3.562500000000159e-06
6.434374999999957e-05
2.66406249999996e-05
3.9062499999978905e-07
-2.2281250000000545e-05
7.700000000000003e-05
7.499999999999181e-07
-2.1250000000002257e-06
4.3124999999999964e-05
1.0171875000000168e-05
2.187499999999768e-06
-0.0
-1.09375

In [1109]:
prob_results

[{'x0u': 0.501875, 'x1u': 0.49374999999999997, 'x2u': 0.50375},
 {'x0u': 0.503375, 'x1u': 0.504, 'x2u': 0.5021249999999999},
 {'x0u': 0.505625, 'x1u': 0.497375, 'x2u': 0.49787499999999996},
 {'x0u': 0.5057499999999999, 'x1u': 0.509875, 'x2u': 0.5077499999999999},
 {'x0u': 0.5065, 'x1u': 0.50525, 'x2u': 0.50425},
 {'x0u': 0.494125, 'x1u': 0.489, 'x2u': 0.502625},
 {'x0u': 0.49837499999999996, 'x1u': 0.502, 'x2u': 0.5029999999999999},
 {'x0u': 0.50925, 'x1u': 0.504625, 'x2u': 0.5105},
 {'x0u': 0.4911249999999999, 'x1u': 0.504875, 'x2u': 0.499},
 {'x0u': 0.49074999999999996, 'x1u': 0.499625, 'x2u': 0.498375},
 {'x0u': 0.504375, 'x1u': 0.503125, 'x2u': 0.488875},
 {'x0u': 0.489375, 'x1u': 0.5035000000000001, 'x2u': 0.495375},
 {'x0u': 0.5033749999999999, 'x1u': 0.496625, 'x2u': 0.499375},
 {'x0u': 0.5015, 'x1u': 0.501375, 'x2u': 0.495625},
 {'x0u': 0.5175000000000001, 'x1u': 0.466375, 'x2u': 0.5082500000000001},
 {'x0u': 0.49799999999999994, 'x1u': 0.50325, 'x2u': 0.494},
 {'x0u': 0.496499

In [1102]:
x1u = 0; x2u = 0; x3u = 0
for key in res_dict:
    if key[0] == '0':
        x1u += res_dict[key]/8000
    if key[1] == '0':
        x2u += res_dict[key]/8000
    if key[2] == '0':
        x3u += res_dict[key]/8000
(2*x1u - 1)*(2*x3u - 1)/4

-7.799999999999947e-05

In [1075]:
x3u

0.488

In [1071]:
res_dict

{'101': 1024,
 '011': 1015,
 '111': 999,
 '001': 1058,
 '110': 971,
 '100': 954,
 '010': 985,
 '000': 994}

In [1090]:
dict_results[-1]

{'101': 993,
 '001': 960,
 '110': 1017,
 '100': 1024,
 '111': 1063,
 '011': 1003,
 '000': 942,
 '010': 998}

In [1037]:
res_dict = res.result().get_counts()
res_dict

{'101': 1024,
 '011': 1015,
 '111': 999,
 '001': 1058,
 '110': 971,
 '100': 954,
 '010': 985,
 '000': 994}

In [1051]:
(res_dict['010'] + res_dict['000'] - res_dict['011'] - res_dict['001'] 
 - res_dict['100'] - res_dict['110'] + res_dict['111'] + res_dict['101'])/(8000 * 4)

0.000125

In [1056]:
x1u = 0; x2u = 0; x3u = 0
for key in res_dict:
    if key[0] == '0':
        x1u += res_dict[key]/8000
    if key[1] == '0':
        x2u += res_dict[key]/8000
    if key[2] == '0':
        x3u += res_dict[key]/8000
(2*x1u - 1)*(2*x3u - 1)/4

-7.799999999999947e-05

In [1046]:
x3u

0.488

In [981]:
(0.9955264412661142)**2 / (2 * 0.005**2)

19821.45790519948

In [1068]:
qc.decompose().draw()

┌─────────────────┐                    ░ ┌─────────────────┐»
   q_0: ┤0                ├────────────────────░─┤0                ├»
        │  circuit-600807 │┌─────────────────┐ ░ │  circuit-600813 │»
   q_1: ┤1                ├┤0                ├─░─┤1                ├»
        └─────────────────┘│  circuit-600810 │ ░ └─────────────────┘»
   q_2: ───────────────────┤1                ├─░────────────────────»
                           └─────────────────┘ ░                    »
meas_0: ════════════════════════════════════════════════════════════»
                                                                    »
meas_1: ════════════════════════════════════════════════════════════»
                                                                    »
meas_2: ════════════════════════════════════════════════════════════»
                                                                    »
«                            ░ ┌─────────────────┐                    ░ »
«   q_0: ────────────────────░─┤0                ├────────────────────░─»
«        ┌─────────────────┐ ░ │  circuit-600819 │┌─────────────────┐ ░ »
«   q_1: ┤0                ├─░─┤1                ├┤0                ├─░─»
«        │  circuit-600816 │ ░ └─────────────────┘│  circuit-600822 │ ░ »
«   q_2: ┤1                ├─░────────────────────┤1                ├─░─»
«        └─────────────────┘ ░                    └─────────────────┘ ░ »
«meas_0: ═══════════════════════════════════════════════════════════════»
«                                                                       »
«meas_1: ═══════════════════════════════════════════════════════════════»
«                                                                       »
«meas_2: ═══════════════════════════════════════════════════════════════»
«                                                                       »
«        ┌─────────────────┐                    ░ ┌─────────────────┐»
«   q_0: ┤0                ├────────────────────░─┤0                ├»
«        │  circuit-600825 │┌─────────────────┐ ░ │  circuit-600831 │»
«   q_1: ┤1                ├┤0                ├─░─┤1                ├»
«        └─────────────────┘│  circuit-600828 │ ░ └─────────────────┘»
«   q_2: ───────────────────┤1                ├─░────────────────────»
«                           └─────────────────┘ ░                    »
«meas_0: ════════════════════════════════════════════════════════════»
«                                                                    »
«meas_1: ════════════════════════════════════════════════════════════»
«                                                                    »
«meas_2: ════════════════════════════════════════════════════════════»
«                                                                    »
«                            ░ ┌─────────────────┐                    ░ »
«   q_0: ────────────────────░─┤0                ├────────────────────░─»
«        ┌─────────────────┐ ░ │  circuit-600837 │┌─────────────────┐ ░ »
«   q_1: ┤0                ├─░─┤1                ├┤0                ├─░─»
«        │  circuit-600834 │ ░ └─────────────────┘│  circuit-600840 │ ░ »
«   q_2: ┤1                ├─░────────────────────┤1                ├─░─»
«        └─────────────────┘ ░                    └─────────────────┘ ░ »
«meas_0: ═══════════════════════════════════════════════════════════════»
«                                                                       »
«meas_1: ═══════════════════════════════════════════════════════════════»
«                                                                       »
«meas_2: ═══════════════════════════════════════════════════════════════»
«                                                                       »
«        ┌─────────────────┐                    ░ ┌─────────────────┐»
«   q_0: ┤0                ├────────────────────░─┤0                ├»
«        │  circuit-600843 │┌─────────────────┐ ░ │  circuit-600849 │»
«   q_1: ┤1                ├┤0        

In [672]:
sum([np.abs(optimal_rep_xx.coeffs[i])/optimal_rep_xx.norm
    for i in range(len(optimal_rep_xx.coeffs))])

1.0000000000000004

In [658]:
optimal_rep_xx.noisy_operations[0].circuit('qiskit').draw()

┌───┐┌────┐
q_0: ┤ X ├┤ √X ├
     ├───┤├───┬┘
q_1: ┤ I ├┤ I ├─
     └───┘└───┘

In [628]:
optimal_rep.coeffs[0]

5.5060403080662236e-05

In [ ]:
self._ideal, self._native_type = convert_to_mitiq(ideal)

In [629]:
optimal_rep.noisy_operations[1].circuit('qiskit').draw()

┌───┐     ┌───┐
q_0: ────┤ I ├─────┤ X ├
     ┌───┴───┴────┐├───┤
q_1: ┤ Rz(-π/400) ├┤ I ├
     └────────────┘└───┘

In [416]:
len(optimal_rep.noisy_operations)

90

In [492]:
sum([abs(m) for m in optimal_rep.coeffs])

2.06608168257626

In [417]:
# Compute PEC linear combination
matrices = [m.channel_matrix for m in optimal_rep.noisy_operations]
mat = sum(m*coeff for (m,coeff) in zip(matrices, optimal_rep.coeffs))
print("Approximated superoperator")
print(mat)
print('------------------------------')
print("Ideal superoperator")
print(noisy_rzz)

Approximated superoperator
[[ 0.999+0.j     0.001+0.001j  0.001+0.001j -0.   +0.j     0.001-0.001j
   0.003+0.j     0.   +0.j     0.   +0.j     0.001-0.001j  0.   +0.j
   0.003+0.j     0.   +0.j    -0.   +0.j     0.   -0.j     0.   -0.j
  -0.   +0.j   ]
 [ 0.001+0.001j  0.921+0.381j -0.   +0.j     0.001+0.001j -0.   +0.001j
  -0.001-0.001j  0.   +0.j     0.   +0.j     0.   +0.j    -0.001-0.001j
   0.   +0.j     0.002+0.001j  0.   -0.j    -0.   +0.j    -0.   +0.j
  -0.   -0.j   ]
 [ 0.001+0.001j -0.   +0.j     0.921+0.381j  0.001+0.001j  0.   +0.j
   0.   +0.j    -0.001-0.001j  0.002+0.001j -0.   +0.001j  0.   +0.j
  -0.001-0.001j  0.   +0.j     0.   -0.j    -0.   +0.j    -0.   +0.j
  -0.   -0.j   ]
 [-0.   +0.j     0.001+0.001j  0.001+0.001j  0.996-0.001j  0.   +0.j
   0.   +0.j     0.001+0.j     0.001-0.001j  0.   +0.j     0.001+0.j
   0.   +0.j     0.001-0.001j -0.   +0.j     0.   -0.j     0.   -0.j
  -0.   +0.j   ]
 [ 0.001-0.001j -0.   -0.001j  0.   +0.j     0.   +0.j     0.921-0.3

In [418]:
print(np.max(mat - noisy_rzz))
# print(np.max(superop_rzz_cirq - noisy_rzz))

(0.001000003166350738+0j)


## Define noisy executor

In [373]:
def ideal_to_noisy_circuit(ideal_circuit):
    noisy_rx = cirq.KrausChannel(cirq.superoperator_to_kraus(superop_rx)).on(cirq.LineQubit(0))
    noisy_rz = cirq.KrausChannel(cirq.superoperator_to_kraus(superop_rz)).on(cirq.LineQubit(0))

    noisy_circuit = cirq.Circuit()
    for op in ideal_circuit.all_operations():
        if op.gate == cirq.rx(np.pi / 2):
            noisy_circuit.append(noisy_rx)
        elif op.gate == cirq.rz(np.pi / 2):
            noisy_circuit.append(noisy_rz)
        else:
            print("Error:", op)

    return noisy_circuit

In [194]:
import pygsti

def cirq_to_pygsti(ideal_circuit: cirq.Circuit):
    pygsti_ops = []
    for op in ideal_circuit.all_operations(): 
        if op.gate == cirq.rx(np.pi / 2):
            pygsti_ops.append(('Gxpi2',0))
        elif op.gate == cirq.rz(np.pi / 2):
            pygsti_ops.append(('Gzpi2',0))
        else:
            print("Error: impossible to simulate operation", op)

    return pygsti.circuits.Circuit(pygsti_ops, line_labels=[0])

In [195]:
def cirq_executor(circuit):
    """Returns the expectation value of the observable A = |1><1|"""
    noisy_circuit = ideal_to_noisy_circuit(circuit)
    rho = cirq.DensityMatrixSimulator().simulate(noisy_circuit).final_density_matrix
    return rho[1, 1].real

def pygsti_executor(circuit):
    """Returns the expectation value of the observable A = |1><1|"""
    noisy_circuit = cirq_to_pygsti(circuit)
    probs = model.probabilities(noisy_circuit)
    return probs["1"]

## Define circuit to mitigate

In [35]:
bit_flip_circuit = cirq_rx + cirq_rx

## Execute without error mitigation

In [46]:
# cirq_executor(bit_flip_circuit)
pygsti_executor(bit_flip_circuit)

0.8278870446802166

## Apply PEC

In [57]:
# execute_with_pec(bit_flip_circuit, cirq_executor, representations=(optimal_rep, ), random_state=0, num_samples=5000)

In [48]:
execute_with_pec(bit_flip_circuit, pygsti_executor, representations=(optimal_rep, ), random_state=0, num_samples=5000)

4.843116547296679

In [495]:
# Modification to the Mitiq function:

def find_optimal_representation_super(
    ideal_operation: QPROGRAM,
    noisy_super_operator: npt.NDArray[np.complex64],
    noisy_basis: NoisyBasis,
    tol: float = 1.0e-8,
    initial_guess: Optional[npt.NDArray[np.float64]] = None,
) -> OperationRepresentation:
    r"""Returns the ``OperationRepresentaiton`` of the input ideal operation
    which minimizes the one-norm of the associated quasi-probability
    distribution.

    More precicely, it solve the following optimization problem:

    .. math::
        \min_{{\eta_\alpha}} = \sum_\alpha |\eta_\alpha|,
        \text{ such that }
        \mathcal G = \sum_\alpha \eta_\alpha \mathcal O_\alpha,

    where :math:`\{\mathcal O_j\}` is the input basis of noisy operations.

    Args:
        ideal_operation: The circuit element to approximate, as a QPROGRAM.
        noisy_super_operator: The noisy super operator to approximate; i.e.,
            the (A) circuit to approximate in terms of (B) circuits, and input
            as a npt.NDArray[np.complex64]
        noisy_basis: The ``NoisyBasis`` in which the ``ideal_operation``
            should be represented. It must contain ``NoisyOperation`` objects
            which are initialized with a numerical superoperator matrix.
        tol: The error tolerance for each matrix element
            of the represented operation.
        initial_guess: Optional initial guess for the coefficients
            :math:`\{ \eta_\alpha \}``.

    Returns: The optimal OperationRepresentation.
    """
    # ideal_cirq_circuit, _ = convert_to_mitiq(ideal_operation)
    # ideal_matrix = kraus_to_super(
    #     cast(List[npt.NDArray[np.complex64]], kraus(ideal_cirq_circuit))
    # )
    ideal_matrix = noisy_super_operator
    basis_set = noisy_basis.elements

    try:
        basis_matrices = [noisy_op.channel_matrix for noisy_op in basis_set]
    except ValueError as err:
        if str(err) == "The channel matrix is unknown.":
            raise ValueError(
                "The input noisy_basis should contain NoisyOperation objects"
                " which are initialized with a numerical superoperator matrix."
            )
        else:
            raise err  # pragma no cover

    # Run numerical optimization problem
    quasi_prob_dist = minimize_one_norm(
        ideal_matrix,
        basis_matrices,
        tol=tol,
        initial_guess=initial_guess,
    )

    basis_expansion = {op: eta for op, eta in zip(basis_set, quasi_prob_dist)}
    return OperationRepresentation(ideal_operation, basis_expansion)